# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0emessages.proto\"!\n\x05\x43laim\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"=\n\x11\x43laimWithArticles\x12\x15\n\x05\x63laim\x18\x01 \x01(\x0b\x32\x06.Claim\x12\x11\n\tfever_ids\x18\x02 \x03(\tb\x06proto3')
)




_CLAIM = _descriptor.Descriptor(
  name='Claim',
  full_name='Claim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Claim.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='Claim.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=51,
)


_CLAIMWITHARTICLES = _descriptor.Descriptor(
  name='ClaimWithArticles',
  full_name='ClaimWithArticles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='claim', full_name='ClaimWithArticles.claim', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fever_ids', full_name='ClaimWithArticles.fever_ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=114,
)

_CLAIMWITHARTICLES.fields_by_name['claim'].message_type = _CLAIM
DESCRIPTOR.message_types_by_name['Claim'] = _CLAIM
DESCRIPTOR.message_types_by_name['ClaimWithArticles'] = _CLAIMWITHARTICLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Claim = _reflection.GeneratedProtocolMessageType('Claim', (_message.Message,), {
  'DESCRIPTOR' : _CLAIM,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Claim)
  })
_sym_db.RegisterMessage(Claim)

ClaimWithArticles = _reflection.GeneratedProtocolMessageType('ClaimWithArticles', (_message.Message,), {
  'DESCRIPTOR' : _CLAIMWITHARTICLES,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ClaimWithArticles)
  })
_sym_db.RegisterMessage(ClaimWithArticles)


# @@protoc_insertion_point(module_scope)
