# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0emessages.proto\"!\n\x05\x43laim\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"6\n\x0e\x43laimWithLines\x12\x15\n\x05\x63laim\x18\x01 \x01(\x0b\x32\x06.Claim\x12\r\n\x05lines\x18\x02 \x03(\t\"H\n\x0e\x45valuatedClaim\x12\x15\n\x05\x63laim\x18\x01 \x01(\x0b\x32\x06.Claim\x12\x10\n\x08\x65vidence\x18\x02 \x03(\t\x12\r\n\x05label\x18\x03 \x01(\tb\x06proto3')
)




_CLAIM = _descriptor.Descriptor(
  name='Claim',
  full_name='Claim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Claim.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='Claim.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=51,
)


_CLAIMWITHLINES = _descriptor.Descriptor(
  name='ClaimWithLines',
  full_name='ClaimWithLines',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='claim', full_name='ClaimWithLines.claim', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lines', full_name='ClaimWithLines.lines', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=107,
)


_EVALUATEDCLAIM = _descriptor.Descriptor(
  name='EvaluatedClaim',
  full_name='EvaluatedClaim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='claim', full_name='EvaluatedClaim.claim', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='evidence', full_name='EvaluatedClaim.evidence', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='EvaluatedClaim.label', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=181,
)

_CLAIMWITHLINES.fields_by_name['claim'].message_type = _CLAIM
_EVALUATEDCLAIM.fields_by_name['claim'].message_type = _CLAIM
DESCRIPTOR.message_types_by_name['Claim'] = _CLAIM
DESCRIPTOR.message_types_by_name['ClaimWithLines'] = _CLAIMWITHLINES
DESCRIPTOR.message_types_by_name['EvaluatedClaim'] = _EVALUATEDCLAIM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Claim = _reflection.GeneratedProtocolMessageType('Claim', (_message.Message,), {
  'DESCRIPTOR' : _CLAIM,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Claim)
  })
_sym_db.RegisterMessage(Claim)

ClaimWithLines = _reflection.GeneratedProtocolMessageType('ClaimWithLines', (_message.Message,), {
  'DESCRIPTOR' : _CLAIMWITHLINES,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ClaimWithLines)
  })
_sym_db.RegisterMessage(ClaimWithLines)

EvaluatedClaim = _reflection.GeneratedProtocolMessageType('EvaluatedClaim', (_message.Message,), {
  'DESCRIPTOR' : _EVALUATEDCLAIM,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:EvaluatedClaim)
  })
_sym_db.RegisterMessage(EvaluatedClaim)


# @@protoc_insertion_point(module_scope)
